import {MARKS, empty, project, merge, pending, decode, encode, connection, syncGitHub, stable} from './sync.mjs';
import {openStore, read, mutate, tabID, onExternalChange, lockSync} from './store.mjs';
import {encodeBackup,decodeBackup} from './backup.mjs';

const $ = s => document.querySelector(s), uid = () => crypto.randomUUID();
const el = (tag, text, cls) => { const e=document.createElement(tag); if(text!=null)e.textContent=text; if(cls)e.className=cls; return e; };
const btn = (text, action, cls) => { const e=el('button',text,cls); e.type='button'; e.onclick=()=>Promise.resolve().then(action).catch(report); return e; };
const paths = {check:'<path d="m4 12 5 5L20 6" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>',heart:'<path d="M12 21S2 15 2 8a5 5 0 0 1 10-1 5 5 0 0 1 10 1c0 7-10 13-10 13" fill="currentColor"/>',star:'<path d="m12 2 3.2 6.3 7 .9-5.1 5 1.2 7-6.3-3.3-6.3 3.3 1.2-7-5.1-5 7-.9Z" fill="currentColor"/>',exclamation:'<path d="M8 5a4 4 0 0 1 8 0l-1.8 10h-4.4Z" fill="currentColor"/><circle cx="12" cy="20" r="2.6" fill="currentColor"/>'};
const names={check:'对勾',heart:'心',star:'星',exclamation:'感叹号'};
function icon(mark){const e=el('span');e.innerHTML=`<svg class="mark-icon" viewBox="0 0 24 24" aria-hidden="true">${paths[mark]}</svg>`;return e;}
const TOKEN_KEY='jiji-github-token-v1';
let state, filterDate='', query='', highlightedID='', selecting=false, anchor=null, chosen=new Set(), token='', busy=false, sending=false, toastTimer, autoTimer, lastSyncAt=0, nextAutoAt=0, autoFailures=0, syncStatus='', pipWindow, pipInput;
try { token=localStorage.getItem(TOKEN_KEY)??''; } catch { /* Private browsing may deny persistent storage. */ }
const input=$('#input'), stream=$('#stream'), dialog=$('#panel'), content=$('#panel-content');
const localDay = t => {const d=new Date(t);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const dateLabel=day=>{const d=new Date(day+'T12:00:00'),today=localDay(Date.now()),yesterday=localDay(Date.now()-86400000);return `${day===today?'今天 · ':day===yesterday?'昨天 · ':''}${d.getFullYear()===new Date().getFullYear()?'':`${d.getFullYear()}年`}${d.getMonth()+1}月${d.getDate()}日`;};
const dateTime = t => new Date(t).toLocaleString('zh-CN',{hour12:false});
const notes = () => state.notes.filter(n=>!n.deletedAt && (!filterDate || n.localDate===filterDate)).sort((a,b)=>a.createdAt-b.createdAt || a.id.localeCompare(b.id));
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3500);}
function report(e){toast(e.message || '操作未完成，请重试');}
function close(){dialog.close();}
function panel(title){content.replaceChildren();const h=el('div',null,'panel-title');h.append(el('span',title),btn('关闭',close));content.append(h);if(!dialog.open)dialog.showModal();return content;}
function field(parent,label,value,type='text'){const wrap=el('label',label,'field'), e=el(type==='textarea'?'textarea':'input');if(type!=='textarea')e.type=type;e.value=value??'';if(type==='password')e.autocomplete='off';wrap.append(e);parent.append(wrap);return e;}
function actions(parent,...buttons){const row=el('div',null,'actions');row.append(...buttons);parent.append(row);}
function preview(parent,text){parent.append(el('div',text,'note-preview'));}
function download(name,data){const blob=new Blob([data],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function stableImportID(prefix,value){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(value)));return prefix+[...new Uint8Array(bytes)].slice(0,16).map(b=>b.toString(16).padStart(2,'0')).join('');}
async function importFullBackup(file){if(file.size>32*1024*1024)throw Error('备份超过 32 MB');const backup=decodeBackup(await file.text()),replacements=[];for(const source of backup.notes)replacements.push(await stableImportID('import-',source));const draftID=await stableImportID('import-draft-',backup.draft);let added=0,adoptDraft=false;
 await update(s=>{const wasEmpty=!s.notes.length&&!Object.values(s.drafts).some(d=>d.text?.trim()||d.versions?.length),existing=new Map(s.notes.map(n=>[n.id,n]));for(const [i,source] of backup.notes.entries()){
  const current=existing.get(source.id);if(current&&stable(current)===stable(source))continue;let note=structuredClone(source);
  if(current){note.id=replacements[i];note.sourceDraftId=null;const versions=[...note.versions,...note.candidates];for(const v of versions)v.id=`${note.id}-${v.id}`;note.syncConflicts=note.syncConflicts.map(v=>({...v,id:`${note.id}-${v.id}`}));}
  if(existing.has(note.id))continue;if(note.sourceDraftId&&s.notes.some(n=>n.sourceDraftId===note.sourceDraftId))note.sourceDraftId=null;s.notes.push(note);existing.set(note.id,note);added++;
 }
 const local=s.drafts[tabID],imported=backup.draft;if(imported.text.trim()||imported.versions.length){if(!local?.text&&!local?.versions?.length){s.drafts[tabID]=imported;adoptDraft=true;}else if(local.text!==imported.text||JSON.stringify(local.versions??[])!==JSON.stringify(imported.versions)){
  if(!existing.has(draftID)){const timestamp=imported.updatedAt||Date.now(),candidates=[...(imported.text.trim()?[{id:`${draftID}-current`,text:imported.text,createdAt:timestamp,label:'导入时',restoredFrom:null}]:[]),...imported.versions.map(v=>({...v,id:`${draftID}-${v.id}`}))].filter((v,i,a)=>v.text.trim()&&a.findIndex(x=>x.text===v.text)===i);if(candidates.length){s.notes.push({id:draftID,text:imported.text,createdAt:timestamp,localDate:imported.localDate||localDay(timestamp),zoneId:imported.zoneId,updatedAt:timestamp,deletedAt:null,recoveredAt:Date.now(),pendingRecovery:true,sourceDraftId:null,versions:[],candidates,editDraft:null,marks:[],syncConflicts:[]});added++;}}
 }}
 if(wasEmpty)s.preferences={name:backup.preferences.displayName,subtitle:backup.preferences.subtitle,placeholder:backup.preferences.placeholder,textSize:backup.preferences.textSize};
 },false,true);if(adoptDraft){input.value=backup.draft.text;if(pipInput)pipInput.value=backup.draft.text;}close();toast(`已导入 ${added} 条记录`);
}
async function update(fn, bottom=false, sync=false){state=await mutate(fn);render();if(bottom)stream.scrollTop=stream.scrollHeight;if(sync)scheduleSync();}
function saveToken(value){token=value.trim();autoFailures=0;nextAutoAt=0;if(!token)syncState('');try{if(token)localStorage.setItem(TOKEN_KEY,token);else localStorage.removeItem(TOKEN_KEY);}catch{toast('浏览器未能记住令牌，本次打开期间仍可同步');}}
function scheduleSync(delay=1800){if(!token||!state||!navigator.onLine||(document.hidden&&(!pipWindow||pipWindow.closed))||Date.now()<nextAutoAt)return;clearTimeout(autoTimer);syncState('等待自动同步');autoTimer=setTimeout(()=>runSync().catch(()=>{}),delay);}
function syncState(text){syncStatus=text;const control=$('#sync-button');control.title=text||'同步';control.setAttribute('aria-label',text||'同步');}
async function runSync({manual=false,config=state.config,credential=token,phase=()=>{}}={}){
 if(busy)return;if(!credential){if(manual)syncPanel();return;}
 clearTimeout(autoTimer);const key=connection(config);busy=true;render();syncState('同步中…');
 try{
  await lockSync(key,async()=>{
   const snapshot=await read(),captured={document:project(snapshot.notes),state:snapshot.bases[key]??{base:empty(),lastSuccess:0}};
   const uploaded=await syncGitHub({...config,token:credential},captured,fetch,phase);
   await update(s=>{const merged=merge(captured.document,project(s.notes),uploaded);s.notes=preserveLocal(s.notes,merged.notes);s.bases[key]={base:uploaded,lastSuccess:Date.now()};});
  });
  lastSyncAt=Date.now();autoFailures=0;nextAutoAt=0;syncState('同步完成');if(manual)toast('同步完成');
 }catch(e){if(!manual){autoFailures++;nextAutoAt=Date.now()+Math.min(15*60000,30000*2**Math.min(autoFailures-1,5));if(e.message?.includes('访问令牌已失效'))nextAutoAt=Infinity;}syncState(`同步未完成：${e.message}`);if(manual)report(e);throw e;}
 finally{busy=false;render();if(token&&pending(project(state.notes),state.bases[key]?.base??empty()))scheduleSync(5000);}
}
function current(id){const n=state.notes.find(n=>n.id===id);if(!n)throw Error('记录不存在');return n;}
function makeVersion(text,label='编辑',restoredFrom=null){return {id:uid(),text,createdAt:Date.now(),label,restoredFrom};}
function changeText(n,text,label='编辑',restoredFrom=null){const v=makeVersion(text,label,restoredFrom);n.text=text;n.updatedAt=v.createdAt;n.versions.unshift(v);n.editDraft=null;n.syncConflicts=(n.syncConflicts??[]).filter(c=>c.text!==text);}
async function copy(list){await navigator.clipboard.writeText(list.map(n=>n.text).join('\n'));toast(`已复制 ${list.length} 条记录`);}
function toggle(id){if(!chosen.size)anchor=id;chosen.has(id)?chosen.delete(id):chosen.add(id);if(!chosen.size)anchor=null;render();}
function range(){if(!anchor)return toast('先选中一条记录');const rows=[...stream.querySelectorAll('.record')],top=stream.getBoundingClientRect().top;const target=rows.find(r=>r.getBoundingClientRect().bottom>top+1);if(!target)return;const all=notes(),a=all.findIndex(n=>n.id===anchor),b=all.findIndex(n=>n.id===target.dataset.id);if(a<0||b<0)return;all.slice(Math.min(a,b),Math.max(a,b)+1).forEach(n=>chosen.add(n.id));render();}
function render(){
 const pos=stream.scrollTop, all=notes();stream.replaceChildren();let day='';
 $('.brand').textContent=state.preferences.name;$('.brand-badge').textContent=state.preferences.name.trim().slice(0,1)||'记';$('#subtitle').textContent=state.preferences.subtitle??'';$('#subtitle').hidden=!state.preferences.subtitle;document.title=state.preferences.name;input.placeholder=state.preferences.placeholder;document.documentElement.style.setProperty('--record-size',`${state.preferences.textSize}px`);
 if(!all.length)stream.append(el('div',filterDate?'没有符合条件的记录':'还没有记录','empty'));
 for(const n of all){
  if(day!==n.localDate){day=n.localDate;stream.append(el('div',dateLabel(day),'day'));}
  const row=el('article',null,`record${chosen.has(n.id)?' selected':''}${highlightedID===n.id?' highlighted':''}`);row.dataset.id=n.id;
  if(selecting){const box=el('input',null,'check');box.type='checkbox';box.checked=chosen.has(n.id);box.setAttribute('aria-label',`选择 ${n.text.slice(0,24)}`);box.onchange=()=>toggle(n.id);row.append(box);}
  const bubble=el('div',null,'bubble'),text=el('div',null,'record-text');if(query&&highlightedID===n.id){const lower=n.text.toLocaleLowerCase(),needle=query.toLocaleLowerCase();let offset=0,found;while((found=lower.indexOf(needle,offset))>=0){text.append(document.createTextNode(n.text.slice(offset,found)),el('mark',n.text.slice(found,found+query.length),'search-hit'));offset=found+query.length;}text.append(document.createTextNode(n.text.slice(offset)));}else text.textContent=n.text;text.onclick=()=>selecting?toggle(n.id):copy([n]).catch(report);bubble.append(text);
  const meta=el('div',null,'record-meta'),marks=el('span',null,'marks');for(const m of n.marks){const i=icon(m);i.title=names[m];marks.append(i);}meta.append(marks,el('time',new Date(n.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false})));
  if(n.pendingRecovery)meta.append(btn('自动恢复',()=>recover(n.id)));
  if(n.syncConflicts?.length)meta.append(btn('选择版本',()=>conflicts(n.id),'warning'));
  meta.append(btn('•••',()=>options(n.id)));bubble.append(meta);row.append(bubble);stream.append(row);
 }
 stream.scrollTop=pos;
 $('#filter-bar').hidden=!(filterDate||query);$('#filter-bar').replaceChildren(el('span',[filterDate,query&&`搜索：${query}`].filter(Boolean).join(' · '),'toolbar-info'),btn('清除筛选',()=>{filterDate='';query='';highlightedID='';render();}));
 $('header').classList.toggle('selecting',selecting);$('#selection-header').hidden=!selecting;$('#selection-count').textContent=`已选 ${chosen.size} 条`;$('#select-button').classList.toggle('active',selecting);$('#select-button').setAttribute('aria-label',selecting?'取消多选':'多选');$('#select-button').title=selecting?'取消多选':'多选';$('#composer').hidden=selecting;$('#selection-bar').hidden=!selecting;$('#range-bar').hidden=!selecting;
 const top=stream.getBoundingClientRect().top,target=[...stream.querySelectorAll('.record')].find(r=>r.getBoundingClientRect().bottom>top+1)?.dataset.id,ids=all.map(n=>n.id),direction=ids.indexOf(target)<=ids.indexOf(anchor)?'↓':'↑';$('#range-bar').replaceChildren(btn(`${direction} 选择到这里`,range));
 $('#selection-bar').replaceChildren(btn('合并复制',()=>copy(notes().filter(n=>chosen.has(n.id)))),btn('标记',()=>markPanel([...chosen])),btn('删除',()=>remove([...chosen])));
 $('#sync-button').classList.toggle('busy',busy);$('#sync-button').disabled=busy;$('#search-button').classList.toggle('active',!!query);$('#date-button').classList.toggle('active',!!filterDate);
 $('#latest-button').hidden=selecting||(!filterDate&&stream.scrollHeight-stream.scrollTop-stream.clientHeight<80);
}
function options(id){const n=current(id),p=panel('记录');preview(p,n.text);actions(p,btn('复制',()=>copy([n])),btn('编辑',()=>edit(id)),btn('标记',()=>markPanel([id])),btn('历史',()=>history(id)),btn('多选',()=>{selecting=true;chosen=new Set([id]);anchor=id;close();render();}),btn('删除',()=>remove([id])));}
function edit(id){const n=current(id),p=panel('编辑'),area=field(p,'内容',n.editDraft?.text??n.text,'textarea');area.oninput=()=>update(s=>{const note=s.notes.find(n=>n.id===id);note.editDraft={text:area.value,updatedAt:Date.now(),selectionStart:area.selectionStart,selectionEnd:area.selectionEnd};}).catch(report);actions(p,btn('保存',async()=>{if(!area.value.trim())return toast('内容不能为空');if(area.value.length>2000000)throw Error('内容过长');await update(s=>changeText(s.notes.find(n=>n.id===id),area.value),false,true);close();},'primary'));area.focus();}
function history(id){const n=current(id),p=panel('消息历史');for(const v of n.versions){const c=el('div',null,'choice');c.append(el('div',`${dateTime(v.createdAt)} · ${v.label}`,'muted'));preview(c,v.text);c.append(btn(v.id===n.versions[0].id?'当前版本':'恢复此版本',async()=>{await update(s=>changeText(s.notes.find(n=>n.id===id),v.text,'恢复',v.id),false,true);close();},'secondary'));p.append(c);}}
function markPanel(ids){if(!ids.length)return toast('先选择记录');const p=panel('标记');for(const mark of MARKS){const active=ids.every(id=>current(id).marks.includes(mark));const b=btn(names[mark],async()=>{await update(s=>{for(const n of s.notes.filter(n=>ids.includes(n.id))){n.marks=active?n.marks.filter(m=>m!==mark):MARKS.filter(m=>m===mark||n.marks.includes(m));n.updatedAt=Date.now();}},false,true);markPanel(ids);},`mark-button${active?' active':''}`);b.prepend(icon(mark));p.append(b);}}
async function remove(ids){if(!ids.length)return toast('先选择记录');await update(s=>{s.notes.filter(n=>ids.includes(n.id)).forEach(n=>{n.deletedAt=Date.now();n.updatedAt=n.deletedAt;});},false,true);chosen.clear();anchor=null;close();render();toast('已移到回收站');}
function trash(){const p=panel('回收站'),list=state.notes.filter(n=>n.deletedAt).sort((a,b)=>b.deletedAt-a.deletedAt);if(!list.length)p.append(el('p','回收站为空','muted'));for(const n of list){const c=el('div',null,'choice');preview(c,n.text);c.append(btn('恢复',async()=>{await update(s=>{const note=s.notes.find(item=>item.id===n.id);note.deletedAt=null;note.updatedAt=Date.now();},false,true);trash();}));p.append(c);}}
function conflicts(id){const n=current(id),p=panel('选择保留的版本');for(const [i,v] of [n.versions[0],...(n.syncConflicts??[])].entries()){const c=el('div',null,'choice');c.append(el('div',i===0?'当前显示':dateTime(v.createdAt),'muted'));preview(c,v.text);c.append(btn('保留此版本',async()=>{await update(s=>{const note=s.notes.find(n=>n.id===id);changeText(note,v.text,'同步后选定',v.id);note.syncConflicts=[];},false,true);close();},'primary'));p.append(c);}}
function recover(id){const n=current(id),p=panel('自动恢复');for(const v of n.candidates??[]){const c=el('div',null,'choice');preview(c,v.text);c.append(btn('保留此版本',async()=>{await update(s=>{const n=s.notes.find(n=>n.id===id);n.text=v.text;n.versions=[makeVersion(v.text,'自动恢复')];n.candidates=[];n.pendingRecovery=false;n.updatedAt=Date.now();},false,true);close();},'primary'));p.append(c);}}
function dates(){const p=panel('日期'),date=field(p,'筛选日期',filterDate||localDay(Date.now()),'date');actions(p,btn('应用',()=>{filterDate=date.value;close();render();},'primary'),btn('今天',()=>{filterDate=localDay(Date.now());close();render();}),btn('所有日期',()=>{filterDate='';close();render();}));}
function search(){const p=panel('搜索'),q=field(p,'内容',query,'search'),results=el('div');p.append(results);const show=()=>{results.replaceChildren();const term=q.value.trim().toLocaleLowerCase();if(!term)return;const matches=state.notes.filter(n=>!n.deletedAt&&n.text.toLocaleLowerCase().includes(term));results.append(el('p',`找到 ${matches.length} 条`,'muted'));for(const n of matches.slice(0,50)){const at=n.text.toLocaleLowerCase().indexOf(term),previewText=n.text.slice(Math.max(0,at-28),at+term.length+55).replace(/\n/g,' ');results.append(btn(`${n.localDate} · ${previewText}`,()=>{query=q.value.trim();filterDate='';highlightedID=n.id;close();render();stream.querySelector(`[data-id="${CSS.escape(n.id)}"]`)?.scrollIntoView({block:'center'});},'setting'));}};q.oninput=show;show();q.focus();}
function draftHistory(){const p=panel('未发送版本历史'),draft=state.drafts[tabID],versions=[...(draft?.text?.trim()?[{id:'current',text:draft.text,createdAt:draft.updatedAt,label:'当前输入'}]:[]),...(draft?.versions??[])];if(!versions.length)p.append(el('p','暂无输入版本','muted'));for(const v of versions){const c=el('div',null,'choice');c.append(el('div',`${dateTime(v.createdAt)} · ${v.label}`,'muted'));preview(c,v.text);actions(c,btn('复制',()=>copy([v])),btn('放回输入框',async()=>{input.value=v.text;if(pipInput)pipInput.value=v.text;await saveDraft(v.text);close();input.focus();},'primary'));p.append(c);}}
function drafts(){const p=panel('草稿箱'),list=Object.entries(state.drafts).filter(([,d])=>d.text?.trim());if(!list.length)p.append(el('p','没有未发送草稿','muted'));for(const [key,d] of list){const c=el('div',null,'choice');c.append(el('div',key===tabID?'当前输入':dateTime(d.updatedAt),'muted'));preview(c,d.text);if(key!==tabID)c.append(btn('添加到输入框',async()=>{const text=[input.value,d.text].filter(Boolean).join('\n');input.value=text;if(pipInput)pipInput.value=text;await saveDraft(text);close();input.focus();}));p.append(c);}}
function inputOptions(){const p=panel('输入选项');p.append(btn('版本历史',draftHistory,'setting'),btn('复制文字',()=>copy([{text:input.value}]),'setting'),btn('桌面浮窗',openFloatingInput,'setting'));}
async function openFloatingInput(){
 if(!('documentPictureInPicture' in window)){toast('此浏览器暂不支持网页置顶浮窗，请在 Mac 上使用 Chrome 或 Edge');return;}
 if(pipWindow&&!pipWindow.closed){pipWindow.focus();close();return;}
 const floating=await documentPictureInPicture.requestWindow({width:340,height:240});pipWindow=floating;
 floating.document.title='自记 · 悬浮输入';floating.document.body.innerHTML='<div class="float-card"><div class="float-head"><strong>自记 ↗</strong><span>⠿</span><button id="float-close" aria-label="收起">⌃</button></div><textarea id="float-input" aria-label="悬浮记录内容" placeholder="记点什么…" maxlength="2000000"></textarea><div class="float-bottom"><span id="float-status">已保存</span><button id="float-send" aria-label="发送记录">↑</button></div></div>';
 const style=floating.document.createElement('style');style.textContent='*{box-sizing:border-box}body{margin:0;padding:12px;background:#f7f8f2;color:#283c33;font-family:-apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif}.float-card{height:100%;padding:10px 13px;border:1px solid #dce2d8;border-radius:17px;background:#fff}.float-head,.float-bottom{display:flex;align-items:center;justify-content:space-between;gap:10px}.float-head strong{font-size:14px;color:#4b7262}.float-head span{color:#738278;cursor:move}.float-head button{border:0;background:none;color:#738278;font-size:20px;cursor:pointer}textarea{width:100%;height:90px;resize:none;border:0;outline:0;padding:8px 0;font-size:16px;line-height:1.6;font-family:inherit;color:#283c33}.float-bottom{font-size:11px;color:#4b7262}.float-bottom button{width:42px;height:42px;border:0;border-radius:11px;background:#4b7262;color:#fff;font-size:24px;cursor:pointer}';floating.document.head.append(style);
 pipInput=floating.document.querySelector('#float-input');pipInput.value=input.value;pipInput.oninput=()=>{input.value=pipInput.value;saveDraft(input.value).then(()=>{if(pipWindow&&!pipWindow.closed)floating.document.querySelector('#float-status').textContent=$('#save-status').textContent;});};floating.document.querySelector('.float-head strong').onclick=()=>window.focus();floating.document.querySelector('#float-send').onclick=()=>$('#send-button').click();floating.document.querySelector('#float-close').onclick=()=>floating.close();floating.addEventListener('pagehide',()=>{pipWindow=null;pipInput=null;});close();pipInput.focus();
}
function settings(){const p=panel('设置'),name=field(p,'名称',state.preferences.name),subtitle=field(p,'副标题',state.preferences.subtitle??''),placeholder=field(p,'输入提示',state.preferences.placeholder),size=field(p,'文字大小',state.preferences.textSize,'number');name.maxLength=12;subtitle.maxLength=48;placeholder.maxLength=60;size.min=14;size.max=24;
 actions(p,btn('保存',async()=>{await update(s=>{s.preferences={name:name.value.trim()||'自记',subtitle:subtitle.value.trim(),placeholder:placeholder.value,textSize:Math.max(14,Math.min(24,Number(size.value)||16))};});close();},'primary'));
 p.append(btn('同步设置',syncPanel,'setting'),btn('版本历史',draftHistory,'setting'),btn('草稿箱',drafts,'setting'),btn('回收站',trash,'setting'),btn('完整备份',()=>download(`自记备份-${localDay(Date.now())}.json`,encodeBackup(state,tabID)),'setting'),btn('导入备份',()=>{const f=el('input');f.type='file';f.accept='.json,application/json';f.onchange=()=>{if(f.files[0])importFullBackup(f.files[0]).catch(report);};f.click();},'setting'),btn('每日 JSON',dailyExport,'setting'),btn('导出同步备份',()=>download(`jiji-sync-${localDay(Date.now())}.json`,encode(project(state.notes))),'setting'),btn('导入同步备份',()=>{const f=el('input');f.type='file';f.accept='.json,application/json';f.onchange=async()=>{try{const file=f.files[0];if(!file)return;if(file.size>32*1024*1024)throw Error('备份超过 32 MB');const doc=decode(await file.text());await update(s=>{const merged=merge(empty(),project(s.notes),doc);s.notes=preserveLocal(s.notes,merged.notes);},false,true);close();toast('已导入');}catch(e){report(e);}};f.click();},'setting'));
 p.append(el('p','草稿保存在当前浏览器；完整备份包含草稿和版本历史。','muted'));
}
function dailyExport(){const p=panel('每日 JSON'),days=[...new Set(state.notes.filter(n=>!n.deletedAt).map(n=>n.localDate))].sort().reverse();if(!days.length)p.append(el('p','暂无记录','muted'));for(const day of days)p.append(btn(day,()=>download(`自记-${day}.json`,JSON.stringify({format:'jiji-daily',schemaVersion:3,localDate:day,exportedAt:Date.now(),notes:state.notes.filter(n=>n.localDate===day&&!n.deletedAt)},null,2)),'setting'));}
function preserveLocal(local, merged){const byID=new Map(local.map(n=>[n.id,n]));return [...local.filter(n=>n.pendingRecovery),...merged.filter(n=>!byID.get(n.id)?.pendingRecovery).map(n=>({...n,editDraft:byID.get(n.id)?.editDraft??null,sourceDraftId:byID.get(n.id)?.sourceDraftId??null}))];}
async function recoverAbandonedDrafts(){if(!navigator.locks)return;for(const key of Object.keys(state.drafts).filter(k=>k!==tabID)){
 await navigator.locks.request('jiji-draft:'+key,{ifAvailable:true},async lock=>{if(!lock)return;await update(s=>{const d=s.drafts[key];if(!d)return;const timestamp=d.updatedAt||Date.now(),id=`recovered-${d.id??key}`;const candidates=[...(d.text?.trim()?[{id:uid(),text:d.text,createdAt:timestamp,label:'最新保存',restoredFrom:null}]:[]),...(d.versions??[])].filter((v,i,a)=>v.text?.trim()&&a.findIndex(x=>x.text===v.text)===i);if(candidates.length&&!s.notes.some(n=>n.id===id))s.notes.push({id,text:d.text??'',createdAt:timestamp,localDate:localDay(timestamp),zoneId:Intl.DateTimeFormat().resolvedOptions().timeZone,updatedAt:timestamp,deletedAt:null,recoveredAt:Date.now(),pendingRecovery:true,sourceDraftId:d.id??key,versions:[],candidates,editDraft:null,marks:[],syncConflicts:[]});delete s.drafts[key];});});
 }}
function syncPanel(){const p=panel('同步'),c=state.config,key=connection(c),last=state.bases[key],count=pending(project(state.notes),last?.base??empty());p.append(el('p',`${count} 条本机更新${last?.lastSuccess?` · 上次 ${dateTime(last.lastSuccess)}`:''}`,'muted'));if(syncStatus.startsWith('同步未完成'))p.append(el('p',syncStatus,'warning'));
 const owner=field(p,'GitHub 用户',c.owner),repo=field(p,'私有仓库',c.repo),branch=field(p,'分支',c.branch),secret=field(p,'访问令牌',token,'password');secret.spellcheck=false;secret.autocapitalize='none';
 const link=el('a','创建仅此仓库的访问令牌');link.href='https://github.com/settings/personal-access-tokens/new';link.target='_blank';link.rel='noopener noreferrer';p.append(link,el('p','令牌保存在此浏览器本机，以便重开网页后自动同步。选择此私有仓库，并允许 Contents 读写。','muted'));
 const status=el('p','','muted');p.append(status);
 const go=btn(busy?'同步中…':'同步',async()=>{
  if(busy)return;const config={owner:owner.value.trim(),repo:repo.value.trim(),branch:branch.value.trim()},credential=secret.value.trim();connection(config);if(!credential)throw Error('请填写访问令牌');
  go.disabled=true;[owner,repo,branch,secret].forEach(e=>e.disabled=true);
  try{await update(s=>{s.config=config;});await runSync({manual:true,config,credential,phase:t=>status.textContent=t});saveToken(credential);syncPanel();}
  catch(e){status.textContent=`${e.message}。本机内容已保留。`;}
  finally{go.disabled=false;[owner,repo,branch,secret].forEach(e=>e.disabled=false);}
 },'primary');go.disabled=busy;actions(p,go,btn('清除令牌',()=>{saveToken('');secret.value='';clearTimeout(autoTimer);toast('令牌已清除');}));
 for(const n of state.notes.filter(n=>n.syncConflicts?.length))p.append(btn(`选择版本 · ${n.text.slice(0,32)}`,()=>conflicts(n.id),'setting'));
}
$('#date-button').onclick=dates;$('#search-button').onclick=search;$('#settings-button').onclick=settings;$('#sync-button').onclick=()=>token?runSync({manual:true}).catch(()=>{}):syncPanel();
$('#select-button').onclick=()=>{selecting=!selecting;chosen.clear();anchor=null;render();};
$('#cancel-selection').onclick=()=>{selecting=false;chosen.clear();anchor=null;render();};
$('#select-all').onclick=()=>{const all=notes().map(n=>n.id);chosen=new Set(all);anchor=all[0]??null;render();};
$('#latest-button').onclick=()=>{filterDate='';query='';highlightedID='';render();stream.scrollTop=stream.scrollHeight;$('#latest-button').hidden=true;};
stream.addEventListener('scroll',()=>{$('#latest-button').hidden=selecting||(!filterDate&&stream.scrollHeight-stream.scrollTop-stream.clientHeight<80);});
$('#input-options-button').onclick=inputOptions;
$('#retry-save-button').onclick=()=>saveDraft(input.value);
$('#copy-draft-button').onclick=()=>copy([{'text':input.value}]).catch(report);
window.addEventListener('storage',e=>{if(e.key!==TOKEN_KEY)return;token=e.newValue??'';autoFailures=0;nextAutoAt=0;if(token)scheduleSync(0);else clearTimeout(autoTimer);});
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}});
stream.addEventListener('click',e=>{if(e.target===stream||e.target.classList.contains('day'))input.blur();});
function saveStatus(text,failed=false){$('#save-status').textContent=text;$('#save-status').classList.toggle('failed',failed);$('#save-actions').hidden=!failed;}
async function saveDraft(text){saveStatus('保存中…');try{state=await mutate(s=>{const old=s.drafts[tabID]??{id:uid(),text:'',versions:[]},now=Date.now(),versions=old.versions??[];if(old.text!==text&&old.text?.trim()){
   let prefix=0,suffix=0;while(prefix<Math.min(old.text.length,text.length)&&old.text[prefix]===text[prefix])prefix++;while(suffix<Math.min(old.text.length-prefix,text.length-prefix)&&old.text[old.text.length-1-suffix]===text[text.length-1-suffix])suffix++;
   const removed=old.text.length-prefix-suffix,inserted=text.length-prefix-suffix,kind=removed===0?'typing':inserted===0?'delete':'replace';
   if((kind==='replace'||kind==='delete'&&old.lastEditKind!=='delete'||now-(old.updatedAt??now)>=1500)&&!versions.some(v=>v.text===old.text))versions.unshift(makeVersion(old.text,text?'输入版本':'清空前'));
   s.drafts[tabID]={...old,text,versions,updatedAt:now,selectionStart:input.selectionStart,selectionEnd:input.selectionEnd,lastEditKind:kind};
  }else s.drafts[tabID]={...old,text,versions,updatedAt:now,selectionStart:input.selectionStart,selectionEnd:input.selectionEnd};});saveStatus('已保存');}catch{saveStatus('保存失败',true);}}
input.oninput=()=>{if(pipInput)pipInput.value=input.value;saveDraft(input.value);};
$('#send-button').onclick=async()=>{if(sending||!input.value.trim())return;sending=true;const text=input.value;if(text.length>2000000){sending=false;return toast('内容过长');}try{await update(s=>{const now=Date.now(),v=makeVersion(text,'发送');s.notes.push({id:uid(),text,createdAt:now,localDate:localDay(now),zoneId:Intl.DateTimeFormat().resolvedOptions().timeZone,updatedAt:now,deletedAt:null,recoveredAt:null,pendingRecovery:false,sourceDraftId:s.drafts[tabID]?.id??null,versions:[v],candidates:[],editDraft:null,marks:[],syncConflicts:[]});if(s.drafts[tabID]?.text===text)delete s.drafts[tabID];},!filterDate||filterDate===localDay(Date.now()),true);if(input.value===text){input.value='';if(pipInput)pipInput.value='';}saveStatus('已保存');}catch(e){report(e);}finally{sending=false;}};
try{await openStore();state=await read();await recoverAbandonedDrafts();input.value=state.drafts[tabID]?.text??'';render();stream.scrollTop=stream.scrollHeight;onExternalChange(async()=>{try{state=await read();render();}catch(e){report(e);}});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});if(token)scheduleSync(0);window.addEventListener('online',()=>scheduleSync(0));document.addEventListener('visibilitychange',()=>{if(!document.hidden&&Date.now()-lastSyncAt>30000)scheduleSync(0);});setInterval(()=>{if((!document.hidden||pipWindow&&!pipWindow.closed)&&Date.now()-lastSyncAt>300000)scheduleSync(0);},60000);}catch(e){stream.replaceChildren(el('p','无法打开本机存储，请允许浏览器保存网站数据后重试。','warning'));$('#send-button').disabled=true;report(e);}
